{"uuid": "185c6e71-d0f7-4ea4-82a9-eb3dac8492c7", "children": ["0ccaa267-3f2f-4dcd-8bb0-9bca7d1bdfa2"], "befores": [{"name": "driver", "status": "passed", "start": 1700317575592, "stop": 1700317576914}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: This alert appeared after 5 seconds\nMessage: unexpected alert open: {Alert text : This alert appeared after 5 seconds}\n  (Session info: chrome=119.0.6045.160)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6975682B2+55298]\n\t(No symbol) [0x00007FF6974D5E02]\n\t(No symbol) [0x00007FF6973905AB]\n\t(No symbol) [0x00007FF69740ACE7]\n\t(No symbol) [0x00007FF6973F1E83]\n\t(No symbol) [0x00007FF6973C670A]\n\t(No symbol) [0x00007FF6973C7964]\n\tGetHandleVerifier [0x00007FF6978E0AAB+3694587]\n\tGetHandleVerifier [0x00007FF69793728E+4048862]\n\tGetHandleVerifier [0x00007FF69792F173+4015811]\n\tGetHandleVerifier [0x00007FF6976047D6+695590]\n\t(No symbol) [0x00007FF6974E0CE8]\n\t(No symbol) [0x00007FF6974DCF34]\n\t(No symbol) [0x00007FF6974DD062]\n\t(No symbol) [0x00007FF6974CD3A3]\n\tBaseThreadInitThunk [0x00007FF89B8B7344+20]\n\tRtlUserThreadStart [0x00007FF89D6226B1+33]\n\n", "trace": "  File \"C:\\Users\\kimma\\github\\automation_qa_course\\env\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\kimma\\github\\automation_qa_course\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"c:\\Users\\kimma\\github\\automation_qa_course\\conftest.py\", line 12, in driver\n    attach = driver.get_screenshot_as_png()\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\kimma\\github\\automation_qa_course\\env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 835, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\kimma\\github\\automation_qa_course\\env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 846, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\kimma\\github\\automation_qa_course\\env\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\kimma\\github\\automation_qa_course\\env\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 228, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1700317604166, "stop": 1700317604171}], "start": 1700317575592, "stop": 1700317604172}